apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: victorqin01/node-calculator-app:1.1.1
    name: nodewebapp
    ports:
    - containerPort: 8000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  